### ISSUE TITLE
Paper for Text Detection Algorithm

### ISSUE THREAD

**Issue by sauradip** [gheinrich/bibnumber#9]
Hii , Nice work , which paper did you consult for implementing the algorithm for text detection ?

**Comment by gheinrich** [comment]
Hello, the text detection pipeline implements the method from http://cmp.felk.cvut.cz/~cernyad2/TextCaptchaPdf/Detecting%20Text%20in%20Natural%20Scenes%20with%20Stroke%20Width%20Transform.pdf.
